#!/usr/bin/env bash
# Transfers a file from Holberton's client to server.
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.


file_to_transfer=""
server_username=""
server_ip=""
ssh_key_path=""

# Check if the correct number of arguments is provided
if [ $# -lt 4 ]
then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
